PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

# Increase EVO Version with each major release.
VLAD_VERSION := 1.0
VLAD_BUILD_TYPE ?= Unofficial

# Internal version
ifeq ($(WITH_GMS),true)
LINEAGE_VERSION := VladOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(VLAD_VERSION)-$(VLAD_BUILD_TYPE)
else
LINEAGE_VERSION := VladOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(VLAD_VERSION)-Vanilla-$(VLAD_BUILD_TYPE)
endif

# Display version
LINEAGE_DISPLAY_VERSION := VladOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(VLAD_VERSION)
